package BrainControl.lib;

import java.io.IOException;
import gnu.io.SerialPort;
import gnu.io.SerialPortEvent;
import gnu.io.SerialPortEventListener;
import gnu.io.CommPortIdentifier;
import gnu.io.PortInUseException;
import gnu.io.UnsupportedCommOperationException;
import java.util.Enumeration;

/**
 * Manages Bluetooth communication for Brain Control application.
 */
public class BtManager implements SerialPortEventListener
{
    private static final int MAX_PACKET_LENGTH = 32;
    private static final int EEG_POWER_BANDS = 8;
    private SerialPort bt;
    private byte lastByte;
    private boolean inPacket = false;
    private boolean freshPacket = false;
    private int packetIndex = 0;
    private int checksumAccumulator = 0;
    private int packetLength = 0;
    private int checksum = 0;
    private int[] eegPower = new int[EEG_POWER_BANDS];
    private byte[] packetData = new byte[MAX_PACKET_LENGTH];

    private int signalQuality = 200;
    private int focus = 0;
    private int meditation = 0;
    
    /**
     * Constructor for objects of class BtManager
     * @param comPort The COM port to connect to the Bluetooth device.
     */
    public BtManager(String comPort)
    {
        super(); // Explicitly calling the superclass constructor
        CommPortIdentifier portId = null;
        Enumeration portEnum = CommPortIdentifier.getPortIdentifiers();

        // Iterate through, looking for the port
        while (portEnum.hasMoreElements()) {
            CommPortIdentifier currPortId = (CommPortIdentifier) portEnum.nextElement();
            if (currPortId.getName().equals(comPort)) {
                portId = currPortId;
                break;
            }
        }

        if (portId == null) {
            System.err.println("Could not find COM port.");
            return;
        }

        try {
            // Open serial port, and use class name for the appName.
            bt = (SerialPort) portId.open(this.getClass().getName(), 2000);

            // Set port parameters
            bt.setSerialPortParams(9600, SerialPort.DATABITS_8, SerialPort.STOPBITS_1, SerialPort.PARITY_NONE);

            // Add event listeners
            bt.addEventListener(this);
            bt.notifyOnDataAvailable(true);
        } catch (PortInUseException | UnsupportedCommOperationException | IOException e) {
            System.err.println(e.toString());
        }
    }

    /**
     * Handles the event generated by SerialPort when data is available.
     * @param oEvent The serial port event
     */
    public synchronized void serialEvent(SerialPortEvent oEvent) {
        if (oEvent.getEventType() == SerialPortEvent.DATA_AVAILABLE) {
            try {
                int available = bt.getInputStream().available();
                byte[] buffer = new byte[available];
                bt.getInputStream().read(buffer, 0, available);

                for (byte b : buffer) {
                    // Process each byte of data here
                }
            } catch (Exception e) {
                System.err.println(e.toString());
            }
        }
    }

    public void start() {
        // Implementation for starting the BtManager
        bt.openPort(); // Corrected method name from Open() to openPort()
    }

    public void stop() {
        if (bt != null) {
            bt.removeEventListener();
            bt.close();
        }
    }
}